### ISSUE TITLE
Cloudflare workers support?

### ISSUE THREAD

**Issue by Zombobot1** [DeepLcom/deepl-node#14]
This library cannot be used in cloudflare workers because it depends on XMLHttpRequest.
Moreover, if I send requests manually they fail with status code 525.

Code to reproduce

```ts
const deepLUrl = 'https://api-free.deepl.com/v2/translate'
const text = 'I like my cat'
const to = 'de'
const from = 'en'

const resp = await fetch(deepLUrl, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    Authorization: `DeepL-Auth-Key ${env.DEEPL}`,
  },
  body: `text=${encodeURIComponent(text)}&target_lang=${to.toUpperCase()}&source_lang=${from.toUpperCase()}`,
})
if (!resp.ok) throw new Error(`DeepL error (${resp.status}) ` + resp.statusText) // throws in workers
const response = await resp.json()
response.translations[0].text // works in node
```

This problem is often mentioned in cloudflare community ([example](https://community.cloudflare.com/t/error-origin-ssl-handshake-error-525/294302/9)). According to cloudflare **"This is typically caused by a configuration issue in the origin web server"**.

Is there any hope for a fix? Cloudflare workers become more and more popular nowadays.

**Comment by daniel-jones-deepl** [comment]
Hi @Zombobot1, thanks for creating the issue; we're looking into it and I'll update you when I have more information.

**Comment by theowenyoung** [comment]
any updates for this?

**Comment by tutankhamen-1** [comment]
I’d appreciate an update on this as well. Currently can’t use the API because of this.

**Comment by croshim** [comment]
Have the same issue, are there any updates?

**Comment by JanEbbing** [comment]
Hi, thanks for the report. I looked into this and I see 2 separate issues.

1. `deepl-node` cannot be used in cloudflare workers as they don't provide a full node environment

There is no good way we can support this - e.g. workers don't have access to any [file system](https://community.cloudflare.com/t/cant-resolve-fs-in-cloudflare-workers/112762) so we could not implement document translation at all, aside from all the basic node functionality we would need to migrate away from.

2. Making direct API requests from a cloudflare worker fails with HTTP Error 525 (SSL Handshake failed)

I looked into this for a while now - e.g. I checked our API with this [SSL test](https://www.ssllabs.com/ssltest/index.html) and it looks correctly configured to me. If I had to guess, cloudflare workers don't seem to offer the right SSL ciphers by default ([the ones they say they offer here would work](https://github.com/cloudflare/sslconfig)), but I have no way to verify that - workers only expose the `fetch` API, which is HTTP-level, and you don't have access to e.g. the `tls` or `https` modules to verify anything.
In addition, I found many user reports about the same problem for many other APIs, which indicates the problem lies with cloudflare workers, not us:
- [1](https://community.cloudflare.com/t/error-origin-ssl-handshake-error-525/294302)
- [2](https://stackoverflow.com/questions/34103323/cloudflare-525-ssl-handshake-failed)
- [3](https://community.cloudflare.com/t/ssl-525-problem-when-calling-an-api-from-cloudflare-worker/356930/3)

So unfortunately it seems cloudflare workers are incompatible with both the client library and our API overall :(
Could you describe your use case to me? Maybe we can find a satisfying solution still.

**Comment by Zombobot1** [comment]
I have opened a corresponding issue in the cloudflare repo. They ask: ["Is zone's SSL mode Full?" ](https://github.com/cloudflare/workerd/issues/776#issuecomment-1595309207)

**Comment by JanEbbing** [comment]
They mean [this setting](https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/full-strict/). As I'm just trying a worker (without a website), I don't think I can access that setting (at least I can't find SSL anywhere) - maybe for you that's different?

I asked internally as well - it seems our Ops team has been talking to cloudflare as well, but couldn't fix the problem. If I had to guess, there is no SSL ciphersuite that both servers support, we are looking into it.

**Comment by JanEbbing** [comment]
Hi, just to give a quick update here - for the API not being reachable at all from cloudflare workers (HTTP Error 525):
We have worked with CloudFlare and identified the issue, this is an issue in CloudFlare workers, and they are working on fixing it.

Just to reiterate, once this is fixed you can manually connect to the DeepL API from CloudFlare workers. As this library needs a full node environment, which is not present on CF workers, the library still won't support CF workers.
We are looking into options to avoid this restriction, in order to offer easier DeepL translations in other environments as well.

**Comment by Zombobot1** [comment]
Thank you. Is there an open issue to track? My issue in the worked repo is kind of stuck.

**Comment by Omarov3000** [comment]
Is there a way to be notified when the deepl is accessible by cloudflare workers? I mean when the 525 error is fixed. We would like to start using it in our company.

**Comment by JanEbbing** [comment]
I think the best way right now is to follow [this ticket](https://github.com/cloudflare/workerd/issues/776) (which you seem to follow already).

For the issue, I will discuss with my team if we should have an issue-tracking repository on Github for the DeepL API. This repository is just for the NodeJS client library (but we get general API questions in all CL repos from time to time), so I think if we keep a tracking issue open it makes the most sense to put it there.

**Comment by Omarov3000** [comment]
Thank you for your amazing work @JanEbbing!

**Comment by J-Giggles** [comment]
Still have the same error as of 05/08/2024

**Comment by OultimoCoder** [comment]
Still broken 1 year later. Crazy how there is no fix.

**Comment by JanEbbing** [comment]
You cannot make a successful request to our API from CF workers even via `cURL` etc, it has nothing to do with axios. You run into the 525 issue. Regardless, I'll take a look at the axios use.

**Comment by MickL** [comment]
Axios should be removed in any case and that would fix this issue. If you cant make a request from CF workers tho, there is something critically wrong with the API. I am using tons of APIs in multiple small and enterprise projects and never had an API that cant be accessed by edge workers.
