### ISSUE TITLE
Type 'string' is not assignable to type 'TargetLanguageCode'

### ISSUE THREAD

**Issue by taishi55** [DeepLcom/deepl-node#15]
**Describe the bug**
[Type error]: I input the target language (string) but deepl.TargetLanguageCode does not allow it. 
```
const defaultLang = "ja";
let typedTargetLang: deepl.TargetLanguageCode = defaultLang;
```

**Type 'string' is not assignable to type 'TargetLanguageCode'.**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by daniel-jones-deepl** [comment]
Hi @taishi55, sorry that it took so long to reply to this issue.

I tried reproducing the problem you described, but I didn't get the same error. The [typescript example](https://github.com/DeepLcom/deepl-node/blob/main/examples/typescript/index.ts#L12) has a similar line to your code, breaking it into two lines like your code didn't cause an error.

I wonder if this problem is because in practice your `defaultLang` variable is not a local variable but is defined somewhere else, and the type information is lost? In that case perhaps attaching the type to this variable might help.
