### ISSUE TITLE
getting overcharged 9 times more

### ISSUE THREAD

**Issue by taishi55** [DeepLcom/deepl-node#16]
**Describe the bug**

Since DeepL API does not understand text in multiple lines, I query just like below. `encodeURIComponent()` is a solution that I was actually suggested by DeepL support.  

```
const inputText = encodeURIComponent(translateText);
const responseDeepL = await axios.post(
      deeplURL,
      `text=${inputText}&target_lang=${targetLang}`,
      {
        headers: {
          Authorization: `DeepL-Auth-Key ${DEEPL_KEY}`,
          "Content-Type": "application/x-www-form-urlencoded",
          "User-Agent": "axios 1.2.0-alpha.1",
        },
      }
    );
```

The problem is the volume of string becomes way larger than the original input.
For example, 
```
const inputText = "こんにちは";
console.log( encodeURIComponent(inputText).length ) // this is 45 characters
console.log( inputText.length ) // this is 5 characters
```

**Comment by taishi55** [comment]
For someone who also get the same suggestion to use `const inputText = encodeURIComponent(translateText)`, I suggest you to use the code below.
`const inputText = translateText.split("\n").join("%0A");`

`encodeURIComponent()` will let you have a super expensive bill

**Comment by daniel-jones-deepl** [comment]
Hi @taishi55 Taishi, thanks for creating this issue.

Firstly, our API does understand text in multiple lines. For example if you translated the following:
```
const multilineText = "こんにちは。\n" +
          "これは複数行のテキストです。\n" +
          "\n" +
          "これは別の段落です。";
```
then `responseDeepL.data.translations[0].text` would give something like `"Hello.\nThis is a multi-line text.\n\nThis is another paragraph."`.

Secondly, you shouldn't be billed for more characters due to using `encodeURIComponent()`. I have just tested your example and confirmed my account is billed 5 characters in your example using `こんにちは`.

You can check your usage using [the `/usage` endpoint](https://www.deepl.com/docs-api/general/get-usage/); the `character_count` field in the response will increment as you make requests. **However there may be a delay** in updates to the value, up to 10 seconds or so. Admittedly this is not very convenient, so we are working on adding a `billed_characters` field to the `/translate` response, so that you can immediately see the number of billed characters with every translate request.

Some further explanation about character encoding:
DeepL API accounts are billed per Unicode character, so `a`, `こ`, and `訳` are each billed as a single character. Punctuation and whitespace are also billed per character, so `。`, space, and newline characters count as single characters. FYI the multi-line example above is billed as 33 characters.

`encodeURIComponent()` is needed to properly encode the text for transmission as an HTTP request. Using this encoding, some characters become longer, for example `こ` is encoded as `%E3%81%93`. However, this encoding is only necessary for transmission over HTTP: DeepL counts characters **after removing this encoding**, so although `こんにちは` is encoded as 45 characters, DeepL bills it as 5 characters.

You should use `encodeURIComponent()` to encode your requests. Some inputs might work as expected (as in your example), but others will not, depending on what characters are contained within the input text.

I hope that this explanation clarifies the situation.

**Comment by taishi55** [comment]
@daniel-jones-deepl 

The `\n` didn't work with the cURL query. The only way of formatting multi-line sentences is to replace the `\n` with `%0A`.

Thanks for the clear explanation. The price description says `$25.00 per 1 million characters`, so I thought `encodeURIComponent ()` let to the high usage. 

In the future, is it possible for us to reduce the price per usage? We might need to switch another translation API due to the constant price-plan regardless of a large-volume of usage.

**Comment by daniel-jones-deepl** [comment]
HI @taishi55,

I have to assume you are not encoding your input text using `encodeURIComponent()` as I suggested. The newline character `\n` needs to be encoded correctly; after URL-encoding it is `%0A` -- this is why your replacement-strategy works. I still recommend using `encodeURIComponent()` to URL-encode your text in case your text contains any other character that requires encoding.

Here is a full example translating multiline-text, you will need to replace your auth key, and `deeplURL` if you are using a DeepL API Free account.
This example translation will be billed 33 characters, that is how many characters are in the unencoded input (including punctuation).
Note that this example does use `encodeURIComponent()`; without this function the request will fail.
```
const DEEPL_KEY = "DEEPL_AUTH_KEY";
const deeplURL = "https://api.deepl.com/v2/translate";
const targetLang = "en-US";
const multilineText = "こんにちは。\n" +
  "これは複数行のテキストです。\n" +
  "\n" +
  "これは別の段落です。";
const encodedText = encodeURIComponent(multilineText);
const responseDeepL = await axios.post(
  deeplURL,
  `text=${encodedText}&target_lang=${targetLang}`,
  {
      headers: {
          Authorization: `DeepL-Auth-Key ${DEEPL_KEY}`,
          "Content-Type": "application/x-www-form-urlencoded",
          "User-Agent": "axios 1.2.0-alpha.1",
      },
  }
);
const translatedText = responseDeepL.data.translations[0].text;
console.log(translatedText);
// Prints: "Hello.\nThis is a multi-line text.\n\nThis is another paragraph."
```

Regarding pricing: unfortunately this is outside of my knowledge. Discounts might be available for high volume customers; you can contact our support team about that.

**Comment by taishi55** [comment]
Thank you for the detail. I restarted using `encodeURIComponent()`. I'll close this since it was my misunderstand. 

I will need to change my app's price plan. The usage was more expensive than I expected (My mistake).

**Comment by Wizzel1** [comment]
@daniel-jones-deepl are there any news about the `billed_characters` property on the translate reponse?
