### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by HLM-yumonnaing** [DeepLcom/deepl-node#29]
We are found when we test to use deepl-node packages in our mobile app.
Package download link..
[deepl-node - npm (npmjs.com)](https://www.npmjs.com/package/deepl-node)

Our app is based on react-native language.
We just use sample code and connection tests with deepl server.

Found err info:
[TypeError: Cannot read property 'prototype' of undefined]

**Comment by JanEbbing** [comment]
Hi, could you please share the full stack trace of the error and the code you use to call the deepl-node library?

**Comment by HLM-yumonnaing** [comment]
Firstly, I found this error after install deepl-node package and run my app.

![image](https://github.com/DeepLcom/deepl-node/assets/123156566/5a19703e-d128-4eb7-8284-08efdf670afe)

So i install fs, http..package manually and rerun my app.
![deepl-capture](https://github.com/DeepLcom/deepl-node/assets/123156566/41078e3a-5efe-408f-a9ce-b96ebde1cac9)

And then after i found [TypeError: Cannot read property 'prototype' of undefined]
![deepl](https://github.com/DeepLcom/deepl-node/assets/123156566/07c3acc3-9355-45a0-9e1f-f50e1c5ac810)

Is this concerned with TypeError.


..sorry for my english...

**Comment by JanEbbing** [comment]
I edited your comment as some of the screenshots contained your API key.
If the module "fs" cannot be found, it means you don't have a full node installation. Are you using some other framework to develop your app, like Ionic (we don't support this use case)?
If you are building an application with pure node, you need to download the Node runtime environment from the [official website](https://nodejs.org/) so that you won't get these missing module errors for fs, http, etc.
Be sure to check the example folder, its an easy way to start a minimal project that uses the DeepL library with Node to translate, and you can go from there.

**Comment by HLM-yumonnaing** [comment]
Thank you for your suggestion.
My app is using React Native.
